apiVersion: v1
kind: Service
metadata:
  name: vprodb
  namespace: default
spec:
  selector:
    app: vprodb
  type: ClusterIP
  sessionAffinityConfig:
  ports:
  - name: MYAPP
    protocol: TCP
    port: 3306
    targetPort: vprodb-port
   