apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vpromq01
  labels:
    name:  vpromq01
spec:
  selector: 
   matchLabels:
    app: vpromq01
  template:
    metadata:
      labels:
        name:  vpromq01
  spec:
    containers:
      - image:  rabbidmq
        name:  vpromq01
        ports:
        - containerPort: 15672
          name:  vpromq01
        env:
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"
                        