apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: default
spec:
  selector:
    app: vproapp-service
  type: LoadBalancer
  ports:
  - name: vproapp-service
    protocol: TCP
    port: 80
    targetPort: vproapp-port
   